const ADD_TODO = "ADD_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const RECEIVE_TODOS = "RECEIVE_TODOS";
const SET_LOGGED_USER = "SET_LOGGED_USER";

export { ADD_TODO, REMOVE_TODO, TOGGLE_TODO, RECEIVE_TODOS, SET_LOGGED_USER };
